[package]
name = "Zion-STC-Contracts"
version = "2.0.1"

[addresses]
StarcoinFramework = "0x1"
ZionBridge = "0xf8ea2d94b8a7d83ace33bb56731268e0"

[dependencies]
# v1.12.9
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "b0a1ca20ac963d23a85da921b049e49ba557f199" }
Poly-STC-Assets = { git = "https://github.com/Elements-Studio/poly-stc-assets", rev = "b0a1ca20ac963d23a85da921b049e49ba557f199" }